### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/Meryalvhe-Formulario-HTML5#1]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- ¡Muy buen proyecto @Meryalvhe  ... ¡Felicidades!
## Estilo de código y limpieza
- ¡Bien hecho!
## Mejores prácticas/comentarios
- Entiendo que aquí 
![Captura de pantalla de 2024-03-14 11-09-48](https://github.com/4GeeksAcademy/Meryalvhe-Formulario-HTML5/assets/139759297/44ee0c57-bf2d-402e-885f-bc805705a57a) tienes un error tipográfico y querías escribir `border`

**Comment by Meryalvhe** [comment]
## ¡Gracias Edo! 🧑🏻‍💻
*Por supuesto, quería escribir* ``border`` *~pero, la dislexia me ganó~*
#### Me lo anoto todo, para tenerlo en cuenta! 🙋🏼‍♀️

**Comment by EduardoHernandezGuzman** [comment]
Buen trabajo
